#!/bin/bash

CN=$1 # Case name.

SS="scripts" # scripts directory.
MD="mesh" # Mesh directory.
MN="main" # Mesh name.
NP=4 # Number of processors.
GD="mesh" # Gmsh executable directory.

./$SS/copySystem "$CN" "simple"

./$SS/makeCase $CN
./$SS/copySystem "$CN" "simple"

#gmsh mesh/main.geo -3 -o mesh/main.msh 

./$SS/moveMesh $CN $MD $MN
./$SS/convertMesh $CN $MN

./$SS/deleteBoundaryEntry $CN "baffle"
./$SS/adjustBoundaryCount $CN -1

./$SS/changeBoundary $CN "wedge0" "wedge" "wedge"
./$SS/changeBoundary $CN "wedge1" "wedge" "wedge"
./$SS/changeBoundary $CN "duct" "wall" "wall"
./$SS/changeBoundary $CN "tunnel" "wall" "wall"

./$SS/rotateMesh $CN "2.5"
./$SS/replace0 $CN "U"

./$SS/createBaffles $CN $SS
./$SS/replace0 $CN "p"

./$SS/optimize $CN $NP
./$SS/check $CN

#./$SS/copySystem $CN "potential"
#./$SS/execute $CN $NP "potentialFoam"

#./$SS/copySystem $CN "pimple"
#./$SS/execute $CN $NP "pimpleFoam"

./$SS/copySystem $CN "simple"
#./$SS/execute $CN $NP "simpleFoam"
cd $CN
simpleFoam > log


