#!/bin/bash

CN=$1 # Case name.
PN=$2 # Patch name.
TT=$3 # Type.
PT=$4 # Physical type.

BF="$CN/constant/polyMesh/boundary" # Boundary file.

line=$(grep -n "$PN" $BF | cut -d: -f1)
line=$((line+2))
sed -i "${line}s/.*/	type		$TT;/" $BF
line=$((line+1))
sed -i "${line}s/.*/	physicalType	$PT;/" $BF
