#!/bin/bash

CN=$1
FF=$2 # Folder in system to replace the current system files.

cd $CN/system

rm controlDict fvSolution fvSchemes
cp $FF/controlDict controlDict
cp $FF/fvSolution fvSolution
cp $FF/fvSchemes fvSchemes

cd ../../
