#!/bin/bash

CN=$1 # Case name.
SF=$2 # Scripts folder.

BF="constant/polyMesh/boundary" # Boundary file.

cd $CN

# Get total number of faces.
CM="checkMesh.out" # Check mesh file name.
checkMesh -constant > $CM
faces=$(sed -n 's/^ *faces: *.*/&/p' $CM)
faces=$(sed 's/faces://g' <<< $faces)
rm $CM

# Add cyclic entries into the boundary file.
SPEC1="baffle { type cyclic;physicalType patch;neighbourPatch baffleother;nFaces 0;startFace $faces; }"
SPEC2="baffleother { type cyclic;physicalType patch;neighbourPatch baffle;nFaces 0;startFace $faces; }"
addon="temp"
echo $SPEC1 > $addon
echo $SPEC2 >> $addon
sed -i "s/startFace.*/startFace\t$faces; }/g" $addon
sed -i "s/)//g" $BF # Delete ending parenthesis.
cat $addon >> $BF # Append the boundary specification.
sed -i '$a )' $BF # Append the ending parenthesis.
rm $addon

cd ../

./$SF/adjustBoundaryCount $CN 2

cd $CN

# Create and split baffles
createBaffles -overwrite -dict system/baffleDict > baffleLog

# After baffle creation, the faceSet files are not updated and are thus wrong.
cd constant/polyMesh/sets
rm baffle
cd ../../../

cd ../
