#!/bin/bash

CN=$1 # Case name.
BN=$2 # Boundary name.

LL=6 # Line numbers in boundary entry.
BF="constant/polyMesh/boundary" # Boundary file.

cd $CN

# Find entry
L1=$(grep -n "$BN" $BF | cut -d: -f1) # Entry start line number.
L2=$((L1+LL)) # Entry end line number.

sed -i "${L1},${L2}d" $BF # Delete lines.

cd ../
