#!/bin/bash

CN=$1 # Case name.
AA=$2 # Angle to rotate, in deg. Positive CCW, Negative CW.

PI=`echo "4*a(1)" | bc -l`
XC=`echo "c($AA*$PI/180)" | bc -l` # x-component.
YC=`echo "s($AA*$PI/180)" | bc -l` # y-component.

cd $CN

rotateMesh "(1 0 0)" "($XC 0 $YC)"
cp "../case/0/U" "0/U"

cd ../
